### PR TITLE
Fix TPS Drop cause by PlayerMoveEvent

### PR DESCRIPTION
**Pull request by Ytnoos**
Avoid creating a task even for small movements

### CODE REVIEW

**Comment by badbones69** [comment]
Were you able to test to see if this was working after you sent the PR. I'll be testing it out when I get a bit of time to make sure it's all working as well.

**Comment by Ytnoos** [comment]
Actually the current branch doesn't even load so I have no way to test it

**Comment by badbones69** [comment]
Thanks, working on testing it all out.

**Comment by badbones69** [comment]
@Ytnoos seems I get an error when closing the server or reloading the plugin from these 2 lines. I disabled the printing which seems to fix the error messages. Tho the error doesn't cause any issues though so it seems fine to shut the error up.

Lines that cause the error: 

https://github.com/badbones69/Crazy-Enchantments/blob/8970c14d8f94b8637fd5c827d4d471b0107d1499/plugin/src/main/java/me/badbones69/crazyenchantments/processors/Processor.java#L18-L19

Error message:

```[01:59:41] [Thread-22/WARN]: java.lang.InterruptedException
[01:59:41] [Thread-22/WARN]: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
[01:59:41] [Thread-22/WARN]: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
[01:59:41] [Thread-22/WARN]: 	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
[01:59:41] [Thread-22/WARN]: 	at me.badbones69.crazyenchantments.processors.Processor.lambda$new$0(Processor.java:15)
[01:59:41] [Thread-22/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:59:41] [Thread-21/WARN]: java.lang.InterruptedException
[01:59:41] [Thread-21/WARN]: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
[01:59:41] [Thread-21/WARN]: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
[01:59:41] [Thread-21/WARN]: 	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
[01:59:41] [Thread-21/WARN]: 	at me.badbones69.crazyenchantments.processors.Processor.lambda$new$0(Processor.java:15)
[01:59:41] [Thread-21/WARN]: 	at java.lang.Thread.run(Thread.java:748)```

**Comment by Ytnoos** [comment]
Oh My bad, just remove the printStackTrace and keep the interrupt inside the catch. It's normal because interrupt(), when the plugin disables, gets called while the loop is iterating.

**Pull request merged**
