### PR TITLE
Support for SuperiorSkyblock

### PR DESCRIPTION
**Pull request by OmerBenGera**

### CODE REVIEW

**Comment by OmerBenGera** [comment]
I forgot to include SSB's API:
https://github.com/OmerBenGera/SuperiorSkyblockAPI

**Comment by RefusingsPaPa** [comment]
Did you add a check in the SupportedPlugins class in the updatePluginStates and the uppdateFactionPlugin methods?

**Comment by OmerBenGera** [comment]
> 
> 
> Did you add a check in the SupportedPlugins class in the updatePluginStates and the uppdateFactionPlugin methods?

I've just checked again. updateFactionPlugin has nothing to do with that, as SuperiorSkyblock is a skyblock plugin. about updatePluginStates: under the default case, it just makes it on true. which means, yeah - it should work

**Comment by RefusingsPaPa** [comment]
kk

**Comment by RefusingsPaPa** [comment]
However, with the inTerritory method, you do need to add that to the inTerritory method in the Support class.

**Comment by badbones69** [comment]
Will add the rest thanks.

**Pull request merged**
